import { randomBytes } from 'crypto';
import { MigrationInterface, QueryRunner } from 'typeorm';

export class ReplaceAutoGeneratedCodes1749200000000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    const rows: { id: string }[] = await queryRunner.query(
      `SELECT id FROM volunteers WHERE volunteer_code LIKE 'SIN-COD-%'`,
    );

    if (rows.length === 0) return;

    // Track codes assigned in this run to avoid intra-migration duplicates
    const usedInRun = new Set<string>();

    for (const row of rows) {
      let code = `GEN-${randomBytes(4).toString('hex').toUpperCase()}`;

      // Re-roll until unique within this run and within the table
      while (true) {
        if (usedInRun.has(code)) {
          code = `GEN-${randomBytes(4).toString('hex').toUpperCase()}`;
          continue;
        }
        // UUIDs and hex codes are alphanumeric-safe for interpolation
        const existing: unknown[] = await queryRunner.query(
          `SELECT id FROM volunteers WHERE volunteer_code = '${code}'`,
        );
        if (existing.length === 0) break;
        code = `GEN-${randomBytes(4).toString('hex').toUpperCase()}`;
      }

      usedInRun.add(code);
      await queryRunner.query(
        `UPDATE volunteers SET volunteer_code = '${code}' WHERE id = '${row.id}'`,
      );
    }
  }

  async down(): Promise<void> {
    // Original SIN-COD- codes cannot be recovered once overwritten
  }
}
